-- Check that the function dispensar_prescripcion exists and whether it's SECURITY DEFINER
-- This query prints autogenerated ALTER / GRANT statements you can execute.

-- 1) Show basic info
SELECT p.oid, p.proname, pg_get_userbyid(p.proowner) AS owner, p.prosecdef
FROM pg_proc p
WHERE p.proname = 'dispensar_prescripcion';

-- 2) Print ALTER FUNCTION to set SECURITY DEFINER (if you want to apply it)
SELECT format('/* Run this to set SECURITY DEFINER for the function: */\nALTER FUNCTION public.%I(%s) SECURITY DEFINER;\n', p.proname, pg_get_function_identity_arguments(p.oid)) AS alter_stmt
FROM pg_proc p
WHERE p.proname = 'dispensar_prescripcion';

-- 3) Print GRANT EXECUTE statements (adjust target role as needed, e.g., 'anon' or specific role)
SELECT format('/* Grant execute to anon (or change to desired role): */\nGRANT EXECUTE ON FUNCTION public.%I(%s) TO anon;\n', p.proname, pg_get_function_identity_arguments(p.oid)) AS grant_stmt
FROM pg_proc p
WHERE p.proname = 'dispensar_prescripcion';

-- 4) If RLS blocks access for the anonymous/role, consider granting table rights to function owner or use SECURITY DEFINER
-- Use the printed ALTER and GRANT statements above in the Supabase SQL editor as a user with sufficient privileges.
