services:
  - type: web
    name: sermed-flask
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.7
      - key: FLASK_ENV
        value: production